version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cycling-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cycling-backend
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/cycling-coach
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: cycling-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cycling-coach

volumes:
  data:
  mongodb_data: