services:
  cycling-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cycling-frontend
    ports:
      - "80:80"
    depends_on:
      - cycling-backend

  cycling-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cycling-backend
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://cycling-mongodb:27017/cycling-coach
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}  # Pass from host environment

    depends_on:
      - cycling-mongodb

  cycling-mongodb:
    image: mongo:latest
    container_name: cycling-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cycling-coach

volumes:
  data:
  mongodb_data: